# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.m_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.m_log.setGeometry(QtCore.QRect(10, 380, 391, 261))
        self.m_log.setObjectName("m_log")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 991, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.m_chenxing = QtWidgets.QWidget()
        self.m_chenxing.setObjectName("m_chenxing")
        self.tabWidget.addTab(self.m_chenxing, "")
        self.m_tiantian = QtWidgets.QWidget()
        self.m_tiantian.setObjectName("m_tiantian")
        self.m_tt_input_zhishu_name = QtWidgets.QLineEdit(self.m_tiantian)
        self.m_tt_input_zhishu_name.setGeometry(QtCore.QRect(20, 40, 151, 21))
        self.m_tt_input_zhishu_name.setObjectName("m_tt_input_zhishu_name")
        self.label = QtWidgets.QLabel(self.m_tiantian)
        self.label.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label.setObjectName("label")
        self.m_tt_btn_search_zhishu = QtWidgets.QPushButton(self.m_tiantian)
        self.m_tt_btn_search_zhishu.setGeometry(QtCore.QRect(190, 40, 75, 23))
        self.m_tt_btn_search_zhishu.setObjectName("m_tt_btn_search_zhishu")
        self.m_tt_btn_search_detail = QtWidgets.QPushButton(self.m_tiantian)
        self.m_tt_btn_search_detail.setGeometry(QtCore.QRect(270, 40, 75, 23))
        self.m_tt_btn_search_detail.setObjectName("m_tt_btn_search_detail")
        self.m_tt_btn_search_drawdown = QtWidgets.QPushButton(self.m_tiantian)
        self.m_tt_btn_search_drawdown.setGeometry(QtCore.QRect(270, 70, 75, 23))
        self.m_tt_btn_search_drawdown.setObjectName("m_tt_btn_search_drawdown")
        self.tabWidget.addTab(self.m_tiantian, "")
        self.m_zhongzheng = QtWidgets.QWidget()
        self.m_zhongzheng.setObjectName("m_zhongzheng")
        self.tabWidget.addTab(self.m_zhongzheng, "")
        self.m_zhongzhai = QtWidgets.QWidget()
        self.m_zhongzhai.setObjectName("m_zhongzhai")
        self.m_info_bond_div_stock = QtWidgets.QPushButton(self.m_zhongzhai)
        self.m_info_bond_div_stock.setGeometry(QtCore.QRect(390, 30, 100, 32))
        self.m_info_bond_div_stock.setObjectName("m_info_bond_div_stock")
        self.m_comb_zz_show_list = QtWidgets.QComboBox(self.m_zhongzhai)
        self.m_comb_zz_show_list.setGeometry(QtCore.QRect(40, 30, 321, 32))
        self.m_comb_zz_show_list.setObjectName("m_comb_zz_show_list")
        self.tabWidget.addTab(self.m_zhongzhai, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.m_chenxing), _translate("MainWindow", "晨星"))
        self.label.setText(_translate("MainWindow", "指数名称"))
        self.m_tt_btn_search_zhishu.setText(_translate("MainWindow", "搜索"))
        self.m_tt_btn_search_detail.setText(_translate("MainWindow", "获取详情"))
        self.m_tt_btn_search_drawdown.setText(_translate("MainWindow", "获取回撤"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.m_tiantian), _translate("MainWindow", "天天"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.m_zhongzheng), _translate("MainWindow", "中证指数"))
        self.m_info_bond_div_stock.setText(_translate("MainWindow", "显示债股比"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.m_zhongzhai), _translate("MainWindow", "中债指数"))
